language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get install libeigen3-dev
  - git clone https://www.github.com/kartikkumar/sml
  - cd sml 
  - git submodule init
  - git submodule update
  - cmake -HSML -Bbuild
  - cd build
  - make
  - cd ..
  - cd ..

install:
  - cmake -HSAM -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DBUILD_WITH_EIGEN=on
  - cd build
  - make
  - cd ..

script:
  - cd build
  - ctest -V